name: "Pull Request Description Adder"
description: "Add or replace the contents of GitHub descriptions"
author: "Derek Roberts"
branding:
  icon: "message-square"
  color: "blue"

inputs:
  append:
    description: "Message to use in PR description"
    required: true
  owner:
    description: "owner"
    required: true
  pr_no:
    description: "pr number"
    required: true
  repo:
    description: "repo"
    required: true
  token:
    description: "Github token"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
