name: "Pull Request Description Adder"
description: "Add or replace the contents of GitHub descriptions"
author: "Derek Roberts"
branding:
  icon: "message-square"
  color: "blue"

inputs:
  message_body:
    description: "Message to use in PR description"
    required: true
  github_token:
    description: "Github token"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
