name: "Add to PR Descriptions"
description: "Add to pull request descriptions using markdown"
author: "Derek Roberts"
branding:
  icon: "message-square"
  color: "blue"

inputs:
  add_markdown:
    description: "Markdown message to use in PR description"
    required: true
  github_token:
    description: "GitHub token or a Personal Access Token (PAT)"
    default: ${{ github.token }}
  limit_to_pr_opened:
    description: "Only run when a PR is opened or reopened, not pushed"
    default: "false"

runs:
  using: "node18"
  main: "dist/index.js"
