name: "Add to PR Descriptions"
description: "Add to pull request descriptions using markdown"
author: "Derek Roberts"
branding:
  icon: "message-square"
  color: "blue"

inputs:
  add_markdown:
    description: "Markdown message to use in PR description"
    required: true
  github_token:
    description: "Usually <dollar sign>{{ secrets.GITHUB_TOKEN }}"
    required: true
  opened_object:
    description: GitHub object to only run on opened or reopened

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "github.event.action: ${{ github.event.action }}"
        echo "opened_object: ${{ inputs.opened_object }}"

    # if: github.event.action == 'opened' || github.event.action == 'reopened'

  # using: "node16"
  # main: "dist/index.js"
