name: "Add to PR Descriptions"
description: "Add to pull request descriptions using markdown"
author: "Derek Roberts"
branding:
  icon: "message-square"
  color: "blue"

inputs:
  add_markdown:
    description: "Markdown message to use in PR description"
    required: true
  github_token:
    description: "Usually <dollar sign>{{ secrets.GITHUB_TOKEN }}"
    required: true
  opened_only:
    description: Only add when PR opened or reopened
    default: "false"

runs:
  using: composite
  steps:
    - if: ${{ inputs.opened_only }} == true && ${{ github.event.action }} != 'opened' && ${{ github.event.action }} != 'reopened'
      shell: bash
      run: |
        echo "Not required, since only running on PR opened or reopened"
        echo "github.event.action: ${{ github.event.action }}"

    - name: Action
      uses: bcgov-nr/action-pr-description-add/add@feat/openedReopened
      with:
        add_markdown: ${{ inputs.add_markdown }}
        github_token: ${{ inputs.github_token }}
