name: Merge

on:
  # push:
  #   branches: [main]
  #   paths:
  #     - 'src/**'
  #     - 'package-lock.json'
  #     - 'package.json'
  #     - 'tsconfig.json'
  #     - 'action.yml'
  # workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    env:
      branch: temp-${{ github.run_number }}
    outputs:
      next: ${{ steps.semver.outputs.next }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Semver
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}

      - name: Git Setup
        if: ${{ steps.semver.outputs.next }}
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git checkout -b ${{ env.branch }}

      - name: Rebuild ./dist
        if: ${{ steps.semver.outputs.next }}
        run: |
          npm run dist
          git add ./dist --force
          git commit -m "Rebuild dist/ directory"

      - name: Tag
        if: ${{ steps.semver.outputs.next }}
        env:
          tag_semver: ${{ steps.semver.outputs.next }}
        run: |
          git push -u origin HEAD:${{ env.branch }}
          git tag -f ${{ env.tag_semver }}
          git push -f origin tag ${{ env.tag_semver }}

      - name: Major Release
        if: ${{ steps.semver.outputs.next }}
        env:
          GH_TOKEN: ${{ github.token }}
          tag_semver: ${{ steps.semver.outputs.next }}
          tag_major: ${{ steps.semver.outputs.nextMajor }}
        run: |
          if [ $(gh release view ${{ env.tag_major }} --json name -q .name) ]; then
            gh release edit ${{ env.tag_major }} --tag ${{ env.tag_semver }}
          else
            gh release create ${{ env.tag_major }} --title ${{ env.tag_major }}
          fi

      - name: Semver Release
        if: ${{ steps.semver.outputs.next }}
        env:
          GH_TOKEN: ${{ github.token }}
          tag_semver: ${{ steps.semver.outputs.next }}
          tag_major: ${{ steps.semver.outputs.nextMajor }}
        run: |
          if [ $(gh release view ${{ env.tag_semver }} --json name -q .name) ]; then
            gh release delete ${{ env.tag_semver }} --yes
          fi
          gh release create ${{ env.tag_semver }} --title ${{ env.tag_semver }} --generate-notes

      - name: Cleanup
        if: always() && ${{ steps.semver.outputs.next }}
        run: |
          git push --delete origin ${{ env.branch }}
