name: PR (queue)
on:
  merge_group:

jobs:
  check-dist:
    name: Check dist/
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # For push, later
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4.0.3
        with:
          node-version: 20.x

      - name: Rebuild the dist/ directory
        run: |
          npm ci
          npm run build
          npm run package

      - name: Commit any changes to dist/
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git config --global user.name "${GITHUB_ACTOR}"
            git add .
            git commit -m "Rebuild dist/ directory"
            git push origin HEAD:${{ github.head_ref }}
          fi
