name: "build-test"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  # build: # make sure build/ci work properly
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: |
  #         npm ci
  #     - run: |
  #         npm run all

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          add_markdown: |
            ---
            # Things!
            ## Excitement!
            [Another link!](https://google.ca)
          github_token: ${{ secrets.GITHUB_TOKEN }}
